theme: jekyll-theme-Cayman
title: REGISTER YOUR CAR HERE
description: Please note we have limited parking. In order to protect our parking spaces for our Hotel Guests and patrons, Bonnington Dublin Hotel introduced clamping in the vicinity of the Hotel.